name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      matrix:
        platform: [x64, ARM64]

    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore /p:Platform=${{ matrix.platform }}

      - name: Test
        if: ${{matrix.platform == 'x64'}}
        run: dotnet test --no-build --verbosity normal /p:Platform=${{ matrix.platform }}

      - name: Get short commit sha
        run: echo "SHORT_SHA=$($env:GITHUB_SHA.Substring(0, 7))" >> $env:GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.platform }}-${{ env.SHORT_SHA }}
          path: |
            Community.PowerToys.Run.Plugin.RiderProjects/bin
          if-no-files-found: error
          overwrite: true
